apiVersion: apps/v1
kind: Deployment
metadata:
  name: Java-application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Java-application
  template:
    metadata:
      labels:
        app: Java-application
    spec:
      containers:
      - name: Java-application
        image: gow1998/demo-1:latest
        ports:
        - containerPort: 8090
