apiVersion: v1
kind: Service
metadata:
  name: Java-application-service
spec:
  selector:
    app: Java-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: NodePort
